# --- !Ups

SET datestyle = "ISO, MDY";

INSERT INTO roles VALUES
    (1, 'LGU', '{1}'),
    (2, 'OCD', '{3, 5}'),
    (3, 'OP', '{5}'),
    (4, 'DPWH', '{1, 2, 3, 4, 5}'),
    (5, 'DBM', '{1, 5, 6}'),
    (6, 'NGA', '{1, 4}');;

INSERT INTO gov_units VALUES
    (DEFAULT, 'Legacy Data', null, 1),
    (DEFAULT, 'Office of Civil Defense', 'OCD', 2),
    (DEFAULT, 'Office of the President', 'OP', 3),
    (DEFAULT, 'Department of Public Works and Highways', 'DPWH', 4),
    (DEFAULT, 'Department of Budget and Management', 'DBM', 5);;
--generated by csvParser.js

COPY gov_units FROM 'gov_units.csv' CSV ENCODING 'ISO_8859_9';;

COPY lgus FROM 'lgus.csv' CSV;;

INSERT INTO users VALUES
    (DEFAULT, 'legacy', 'Legacy Data', crypt('password', gen_salt('bf')), 1, true),
    (DEFAULT, 'disasteraffected', 'Disaster-Affected Area', crypt('getsupport', gen_salt('bf')), 1, true),
    (DEFAULT, 'ocd_test', 'OCD Test', crypt('getsupport', gen_salt('bf')), 2, true),
    (DEFAULT, 'op_test', 'OP Test', crypt('getsupport', gen_salt('bf')), 3, true),
    (DEFAULT, 'dpwh_test', 'DPWH Test', crypt('getsupport', gen_salt('bf')), 4, true),
    (DEFAULT, 'dbm_test', 'DBM Test', crypt('getsupport', gen_salt('bf')), 5, true),
    (DEFAULT, 'brgyoza', 'Brenda Repolyo Gyoza', crypt('password', gen_salt('bf')), 1, true),
    (DEFAULT, 'ocdeguzman', 'Oscar Clamidio De Guzman', crypt('password', gen_salt('bf')), 2, true),
    (DEFAULT, 'bsaquinoiii', 'Benigno S. Aquino III', crypt('password', gen_salt('bf')), 3, true),
    (DEFAULT, 'dpwhereford', 'David Pena Whereford', crypt('password', gen_salt('bf')), 4, true),
    (DEFAULT, 'dbmoya', 'Dersecretary Bon Moya', crypt('password', gen_salt('bf')), 5, true);;

# --- !Downs

TRUNCATE events CASCADE;;
ALTER SEQUENCE events_event_id_seq RESTART WITH 1;;

TRUNCATE reqs CASCADE;;
ALTER SEQUENCE reqs_req_id_seq RESTART WITH 1;;

TRUNCATE users CASCADE;;
ALTER SEQUENCE users_user_id_seq RESTART WITH 1;;

TRUNCATE lgus CASCADE;;

TRUNCATE gov_units CASCADE;;
ALTER SEQUENCE gov_units_gov_unit_id_seq RESTART WITH 1;;

TRUNCATE roles CASCADE;;
