# --- !Ups

UPDATE users SET gov_unit_id = 27541 WHERE gov_unit_id = 30;;
DELETE FROM gov_units WHERE gov_unit_id = 30;;
UPDATE users SET gov_unit_id = 27530 WHERE gov_unit_id = 29;;
DELETE FROM gov_units WHERE gov_unit_id = 29;;
UPDATE users SET gov_unit_id = 16193 WHERE gov_unit_id = 25;;
DELETE FROM gov_units WHERE gov_unit_id = 25;;
UPDATE users SET gov_unit_id = 21486 WHERE gov_unit_id = 43;;
DELETE FROM gov_units WHERE gov_unit_id = 43;;
UPDATE users SET gov_unit_id = 460 WHERE gov_unit_id = 51;;
DELETE FROM gov_units WHERE gov_unit_id = 51;;
UPDATE users SET gov_unit_id = 2981 WHERE gov_unit_id = 36;;
DELETE FROM gov_units WHERE gov_unit_id = 36;;
UPDATE users SET gov_unit_id = 18988 WHERE gov_unit_id = 27;;
DELETE FROM gov_units WHERE gov_unit_id = 27;;
UPDATE users SET gov_unit_id = 4367 WHERE gov_unit_id = 59;;
DELETE FROM gov_units WHERE gov_unit_id = 59;;
UPDATE users SET gov_unit_id = 41431 WHERE gov_unit_id = 14;;
DELETE FROM gov_units WHERE gov_unit_id = 14;;
UPDATE users SET gov_unit_id = 32844 WHERE gov_unit_id = 8;;
DELETE FROM gov_units WHERE gov_unit_id = 8;;
UPDATE users SET gov_unit_id = 1969 WHERE gov_unit_id = 58;;
DELETE FROM gov_units WHERE gov_unit_id = 58;;
UPDATE users SET gov_unit_id = 43287 WHERE gov_unit_id = 28;;
DELETE FROM gov_units WHERE gov_unit_id = 28;;
UPDATE users SET gov_unit_id = 20815 WHERE gov_unit_id = 52;;
DELETE FROM gov_units WHERE gov_unit_id = 52;;
UPDATE users SET gov_unit_id = 14657 WHERE gov_unit_id = 16;;
DELETE FROM gov_units WHERE gov_unit_id = 16;;
UPDATE users SET gov_unit_id = 16194 WHERE gov_unit_id = 49;;
DELETE FROM gov_units WHERE gov_unit_id = 49;;
UPDATE users SET gov_unit_id = 10736 WHERE gov_unit_id = 45;;
DELETE FROM gov_units WHERE gov_unit_id = 45;;
UPDATE users SET gov_unit_id = 39593 WHERE gov_unit_id = 44;;
DELETE FROM gov_units WHERE gov_unit_id = 44;;
UPDATE users SET gov_unit_id = 10043 WHERE gov_unit_id = 21;;
DELETE FROM gov_units WHERE gov_unit_id = 21;;
UPDATE users SET gov_unit_id = 15685 WHERE gov_unit_id = 20;;
DELETE FROM gov_units WHERE gov_unit_id = 20;;
UPDATE users SET gov_unit_id = 17269 WHERE gov_unit_id = 53;;
DELETE FROM gov_units WHERE gov_unit_id = 53;;
UPDATE users SET gov_unit_id = 43523 WHERE gov_unit_id = 47;;
DELETE FROM gov_units WHERE gov_unit_id = 47;;
UPDATE users SET gov_unit_id = 9980 WHERE gov_unit_id = 18;;
DELETE FROM gov_units WHERE gov_unit_id = 18;;
UPDATE users SET gov_unit_id = 1935 WHERE gov_unit_id = 12;;
DELETE FROM gov_units WHERE gov_unit_id = 12;;
UPDATE users SET gov_unit_id = 366 WHERE gov_unit_id = 32;;
DELETE FROM gov_units WHERE gov_unit_id = 32;;
UPDATE users SET gov_unit_id = 18404 WHERE gov_unit_id = 13;;
DELETE FROM gov_units WHERE gov_unit_id = 13;;
UPDATE users SET gov_unit_id = 461 WHERE gov_unit_id = 17;;
DELETE FROM gov_units WHERE gov_unit_id = 17;;
UPDATE users SET gov_unit_id = 5298 WHERE gov_unit_id = 9;;
DELETE FROM gov_units WHERE gov_unit_id = 9;;
UPDATE users SET gov_unit_id = 21342 WHERE gov_unit_id = 19;;
DELETE FROM gov_units WHERE gov_unit_id = 19;;
UPDATE users SET gov_unit_id = 7304 WHERE gov_unit_id = 50;;
DELETE FROM gov_units WHERE gov_unit_id = 50;;
UPDATE users SET gov_unit_id = 9264 WHERE gov_unit_id = 48;;
DELETE FROM gov_units WHERE gov_unit_id = 48;;
UPDATE users SET gov_unit_id = 39784 WHERE gov_unit_id = 54;;
DELETE FROM gov_units WHERE gov_unit_id = 54;;
UPDATE users SET gov_unit_id = 4587 WHERE gov_unit_id = 60;;
DELETE FROM gov_units WHERE gov_unit_id = 60;;
UPDATE users SET gov_unit_id = 23751 WHERE gov_unit_id = 26;;
DELETE FROM gov_units WHERE gov_unit_id = 26;;
UPDATE users SET gov_unit_id = 10924 WHERE gov_unit_id = 46;;
DELETE FROM gov_units WHERE gov_unit_id = 46;;
UPDATE users SET gov_unit_id = 41198 WHERE gov_unit_id = 15;;
DELETE FROM gov_units WHERE gov_unit_id = 15;;
UPDATE users SET gov_unit_id = 31933 WHERE gov_unit_id = 7;;
DELETE FROM gov_units WHERE gov_unit_id = 7;;
UPDATE users SET gov_unit_id = 34290 WHERE gov_unit_id = 31;;
DELETE FROM gov_units WHERE gov_unit_id = 31;;
UPDATE users SET gov_unit_id = 36548 WHERE gov_unit_id = 40;;
DELETE FROM gov_units WHERE gov_unit_id = 40;;
UPDATE users SET gov_unit_id = 23053 WHERE gov_unit_id = 55;;
DELETE FROM gov_units WHERE gov_unit_id = 55;;
UPDATE users SET gov_unit_id = 9967 WHERE gov_unit_id = 10;;
DELETE FROM gov_units WHERE gov_unit_id = 10;;
UPDATE users SET gov_unit_id = 460 WHERE gov_unit_id = 51;;
DELETE FROM gov_units WHERE gov_unit_id = 51;;

# --- !Downs

INSERT INTO gov_units VALUES (51, 'ORIENTAL MINDORO', NULL, 1);;
UPDATE users SET gov_unit_id = 51 WHERE gov_unit_id = 460;;
INSERT INTO gov_units VALUES (10, 'ZAMBALES', NULL, 1);;
UPDATE users SET gov_unit_id = 10 WHERE gov_unit_id = 9967;;
INSERT INTO gov_units VALUES (55, 'BRGY PRESIDENT ROXAS, CAPIZ', NULL, 1);;
UPDATE users SET gov_unit_id = 55 WHERE gov_unit_id = 23053;;
INSERT INTO gov_units VALUES (40, 'ALICIA, ZAMBOANGA SIBUGAY', NULL, 1);;
UPDATE users SET gov_unit_id = 40 WHERE gov_unit_id = 36548;;
INSERT INTO gov_units VALUES (31, 'SAN RICARDO, SOUTHERN LEYTE', NULL, 1);;
UPDATE users SET gov_unit_id = 31 WHERE gov_unit_id = 34290;;
INSERT INTO gov_units VALUES (7, 'SAN ISIDRO, LEYTE', NULL, 1);;
UPDATE users SET gov_unit_id = 7 WHERE gov_unit_id = 31933;;
INSERT INTO gov_units VALUES (15, 'SEN SALIPADA K PENDATUN, MAGUINDANAO', NULL, 1);;
UPDATE users SET gov_unit_id = 15 WHERE gov_unit_id = 41198;;
INSERT INTO gov_units VALUES (46, 'NASUGBU, BATANGAS', NULL, 1);;
UPDATE users SET gov_unit_id = 46 WHERE gov_unit_id = 10924;;
INSERT INTO gov_units VALUES (26, 'DUMANGAS, ILOILO', NULL, 1);;
UPDATE users SET gov_unit_id = 26 WHERE gov_unit_id = 23751;;
INSERT INTO gov_units VALUES (60, 'SUAL, PANGASINAN', NULL, 1);;
UPDATE users SET gov_unit_id = 60 WHERE gov_unit_id = 4587;;
INSERT INTO gov_units VALUES (54, 'DOLORES, ABRA', NULL, 1);;
UPDATE users SET gov_unit_id = 54 WHERE gov_unit_id = 39784;;
INSERT INTO gov_units VALUES (48, 'CANDABA, PAMPANGA', NULL, 1);;
UPDATE users SET gov_unit_id = 48 WHERE gov_unit_id = 9264;;
INSERT INTO gov_units VALUES (50, 'MADELLA, QUIRINO', NULL, 1);;
UPDATE users SET gov_unit_id = 50 WHERE gov_unit_id = 7304;;
INSERT INTO gov_units VALUES (19, 'BOSTON, DAVAO ORIENTAL', NULL, 1);;
UPDATE users SET gov_unit_id = 19 WHERE gov_unit_id = 21342;;
INSERT INTO gov_units VALUES (9, 'PIAT, CAGAYAN', NULL, 1);;
UPDATE users SET gov_unit_id = 9 WHERE gov_unit_id = 5298;;
INSERT INTO gov_units VALUES (17, 'POLA, ORIENTAL MINDORO', NULL, 1);;
UPDATE users SET gov_unit_id = 17 WHERE gov_unit_id = 461;;
INSERT INTO gov_units VALUES (13, 'LIBONA, BUKIDNON', NULL, 1);;
UPDATE users SET gov_unit_id = 13 WHERE gov_unit_id = 18404;;
INSERT INTO gov_units VALUES (32, 'LUBANG, OCCIDENTAL MINDORO', NULL, 1);;
UPDATE users SET gov_unit_id = 32 WHERE gov_unit_id = 366;;
INSERT INTO gov_units VALUES (12, 'VINTAR, ILOCOS NORTE', NULL, 1);;
UPDATE users SET gov_unit_id = 12 WHERE gov_unit_id = 1935;;
INSERT INTO gov_units VALUES (18, 'SAN MARCELINO, ZAMBALES', NULL, 1);;
UPDATE users SET gov_unit_id = 18 WHERE gov_unit_id = 9980;;
INSERT INTO gov_units VALUES (47, 'TRENTO, AGUSAN DEL SUR', NULL, 1);;
UPDATE users SET gov_unit_id = 47 WHERE gov_unit_id = 43523;;
INSERT INTO gov_units VALUES (53, 'STA MAGDALENA, SORSOGON', NULL, 1);;
UPDATE users SET gov_unit_id = 53 WHERE gov_unit_id = 17269;;
INSERT INTO gov_units VALUES (20, 'PRESENTACION, CAMARINES SUR', NULL, 1);;
UPDATE users SET gov_unit_id = 20 WHERE gov_unit_id = 15685;;
INSERT INTO gov_units VALUES (21, 'SUBIC, ZAMBALES', NULL, 1);;
UPDATE users SET gov_unit_id = 21 WHERE gov_unit_id = 10043;;
INSERT INTO gov_units VALUES (44, 'PILAR, ABRA', NULL, 1);;
UPDATE users SET gov_unit_id = 44 WHERE gov_unit_id = 39593;;
INSERT INTO gov_units VALUES (45, 'LIAN, BATANGAS', NULL, 1);;
UPDATE users SET gov_unit_id = 45 WHERE gov_unit_id = 10736;;
INSERT INTO gov_units VALUES (49, 'VIGA, CATANDUANES', NULL, 1);;
UPDATE users SET gov_unit_id = 49 WHERE gov_unit_id = 16194;;
INSERT INTO gov_units VALUES (16, 'ANGONO, RIZAL', NULL, 1);;
UPDATE users SET gov_unit_id = 16 WHERE gov_unit_id = 14657;;
INSERT INTO gov_units VALUES (52, 'STA MARIA, DAVAO DEL SUR', NULL, 1);;
UPDATE users SET gov_unit_id = 52 WHERE gov_unit_id = 20815;;
INSERT INTO gov_units VALUES (28, 'BUTUAN CITY, AGUSAN DEL NORTE', NULL, 1);;
UPDATE users SET gov_unit_id = 28 WHERE gov_unit_id = 43287;;
INSERT INTO gov_units VALUES (58, 'ADAMS, ILOCOS NORTE', NULL, 1);;
UPDATE users SET gov_unit_id = 58 WHERE gov_unit_id = 1969;;
INSERT INTO gov_units VALUES (8, 'SAN ROQUE, NORTHERN SAMAR', NULL, 1);;
UPDATE users SET gov_unit_id = 8 WHERE gov_unit_id = 32844;;
INSERT INTO gov_units VALUES (14, 'AMPATUAN, MAGUINDANAO', NULL, 1);;
UPDATE users SET gov_unit_id = 14 WHERE gov_unit_id = 41431;;
INSERT INTO gov_units VALUES (59, 'SAN FABIAN, PANGASINAN', NULL, 1);;
UPDATE users SET gov_unit_id = 59 WHERE gov_unit_id = 4367;;
INSERT INTO gov_units VALUES (27, 'MATUNGAO, LANAO DEL NORTE', NULL, 1);;
UPDATE users SET gov_unit_id = 27 WHERE gov_unit_id = 18988;;
INSERT INTO gov_units VALUES (36, 'LA UNION', NULL, 1);;
UPDATE users SET gov_unit_id = 36 WHERE gov_unit_id = 2981;;
INSERT INTO gov_units VALUES (51, 'ORIENTAL MINDORO', NULL, 1);;
UPDATE users SET gov_unit_id = 51 WHERE gov_unit_id = 460;;
INSERT INTO gov_units VALUES (43, 'COMPOSTELA VALLEY 1ST DISTRICT', NULL, 1);;
UPDATE users SET gov_unit_id = 43 WHERE gov_unit_id = 21486;;
INSERT INTO gov_units VALUES (25, 'CATANDUANES, LONE DISTRICT', NULL, 1);;
UPDATE users SET gov_unit_id = 25 WHERE gov_unit_id = 16193;;
INSERT INTO gov_units VALUES (29, 'BRGY ALEJAWAN, JAGNA, BOHOL', NULL, 1);;
UPDATE users SET gov_unit_id = 29 WHERE gov_unit_id = 27530;;
INSERT INTO gov_units VALUES (30, 'BRGY CANTAGAY, JAGNA, BOHOL', NULL, 1);;
UPDATE users SET gov_unit_id = 30 WHERE gov_unit_id = 27541;;
