# --- !Ups

CREATE TABLE oparr (
    agency text,
    attached_agency text,
    sector_as_given_by_the_agencies text,
    region text,
    province text,
    municipality text,
    title_of_major_program text,
    sub_major_program text,
    program_projects_and_activities_ppa text,
    sub_program_projects_and_activities_ppa text,
    responsible_agency text,
    physical_targets_2014 text,
    physical_targets_2015 text,
    physical_targets_2016 text,
    physical_targets_total text,
    physical_targets_unit text,
    infrastructure_for_doh_only text,
    equipment_for_doh_only text,
    funding_requirements_2014_agency text,
    funding_requirements_2014_govt text,
    funding_requirements_2014_govt_source text,
    funding_requirements_2014_private text,
    funding_requirements_2014_private_source text,
    funding_requirements_2014_total_others text,
    funding_requirements_2014_total_funding text,
    funding_requirements_2015_agency text,
    funding_requirements_2015_govt text,
    funding_requirements_2015_govt_source text,
    funding_requirements_2015_private text,
    funding_requirements_2015_private_source text,
    funding_requirements_2015_total_others text,
    funding_requirements_2015_total_funding text,
    funding_requirements_2016_agency text,
    funding_requirements_2016_govt text,
    funding_requirements_2016_govt_source text,
    funding_requirements_2016_private text,
    funding_requirements_2016_private_source text,
    funding_requirements_2016_total_others text,
    funding_requirements_2016_total_funding text,
    funding_requirements_total_agency text,
    funding_requirements_total_govt text,
    funding_requirements_total_govt_source text,
    funding_requirements_total_private text,
    funding_requirements_total_private_source text,
    funding_requirements_total_total_others text,
    funding_requirements_total_total_funding text,
    funded text,
    for_funding text,
    comments_funded_for_funding text,
    comments_1 text,
    comments_2 text,
    division_for_deped_only text,
    barangay_for_deped_only text,
    priority text,
    number_of_city text,
    category text,
    type_of_project text,
    sub_type text,
    physical_targets_2014_new_classrooms_for_deped_only text,
    physical_targets_2014_repair_of_classrooms_for_deped_only text
);;

COPY oparr FROM 'oparr.csv' CSV ENCODING 'ISO_8859_9';;

# --- !Downs

DROP TABLE IF EXISTS oparr;;
