/* AUTOGENERATED */
package recon.models

import recon.support._

sealed class DisasterType(override val name: String) extends PGObject("disaster_type", name) with DisasterType.Value
object DisasterType extends Enum[DisasterType] {
  val EARTHQUAKE = new DisasterType("Earthquake")
  val FLOOD = new DisasterType("Flood")
  val TYPHOON = new DisasterType("Typhoon")
  val LANDSLIDE = new DisasterType("Landslide")
  val ANTHROPOGENIC = new DisasterType("Anthropogenic")
}

sealed class UserType(override val name: String) extends PGObject("user_type", name) with UserType.Value
object UserType extends Enum[UserType] {
  val LGU = new UserType("LGU")
  val GOCC = new UserType("GOCC")
  val NGA = new UserType("NGA")
  val OCD = new UserType("OCD")
  val ASSESSING_AGENCY = new UserType("ASSESSING_AGENCY")
  val OP = new UserType("OP")
  val DBM = new UserType("DBM")
}

sealed class ProjectType(override val name: String) extends PGObject("project_type", name) with ProjectType.Value
object ProjectType extends Enum[ProjectType] {
  val INFRASTRUCTURE = new ProjectType("Infrastructure")
  val AGRICULTURE = new ProjectType("Agriculture")
  val SCHOOL_BUILDING = new ProjectType("School Building")
  val HEALTH_FACILITIES = new ProjectType("Health Facilities")
  val SHELTER_UNITS = new ProjectType("Shelter Units")
  val ENVIRONMENT = new ProjectType("Environment")
  val OTHER = new ProjectType("Other")
}
