/*
 * Copyright (c) 2014 By Implication, Inc. under the terms of the
 * ISC license found in LICENSE.txt
 */

/* AUTOGENERATED */
package recon.models

import recon.support._

sealed class ProjectScope(override val name: String) extends PGObject("project_scope", name) with ProjectScope.Value
object ProjectScope extends Enum[ProjectScope] {
  val RECONSTRUCTION = new ProjectScope("Reconstruction")
  val REPAIR = new ProjectScope("Repair")
  val PREVENTION = new ProjectScope("Prevention")
  val OTHERS = new ProjectScope("Others")
  val list = List(RECONSTRUCTION, REPAIR, PREVENTION, OTHERS)
}
